name: Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      VIRTUAL_ENV: ${{ github.workspace }}/.venv
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Run tests
        run: make gha-tests
